baseURL = "https://istj.dev"
title = "istj.dev"
languageCode = "en-us"
theme = "devise"
relativeURLs = true
enableEmoji = true
googleAnalytics = ""
enableRobotsTXT = true
copyright = "© 2025 by istj.dev. All rights reserved."

# Main menu items
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = -110
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = -100

# Configuration Features
[params]
  description = "Software Engineer"
  header_title = "I’m istjdev 👋"
  header_subtitle = "Software Engineer | VN"
  home_image = "/images/avatar.png"
  recent_posts = 5
  mainSections = ["posts", "post", "blog"]
  [params.style]
    backgroundColor = "#f8f9fa"
    homeImageBorderColor = "#ffffff"
    fontFamilyBase = "Helvetica Neue"
    fontColor = "#212529"
  [[params.social]]
    fa_icon = "fab fa-github fa-1x"
    href = "http://github.com/istjdev"
  [[params.social]]
    fa_icon = "fab fa-linkedin-in fa-1x"
    href = "https://www.linkedin.com/in/istjdev"
  [[params.social]]
    fa_icon = "fab fa-x-twitter fa-1x"
    href = "https://x.com/istjdev"
[[params.social]]
    fa_icon = "fas fa-envelope fa-1x"
    href = "mailto:istjdev@gmail.com"
